
package com.trining.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyConverter", targetNamespace = "http://ifaces.trining.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyConverter {


    /**
     * 
     * @param usd
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dollarToRupees", targetNamespace = "http://ifaces.trining.com/", className = "com.trining.clients.DollarToRupees")
    @ResponseWrapper(localName = "dollarToRupeesResponse", targetNamespace = "http://ifaces.trining.com/", className = "com.trining.clients.DollarToRupeesResponse")
    @Action(input = "http://ifaces.trining.com/CurrencyConverter/dollarToRupeesRequest", output = "http://ifaces.trining.com/CurrencyConverter/dollarToRupeesResponse")
    public double dollarToRupees(
        @WebParam(name = "usd", targetNamespace = "")
        double usd);

}
